const colors = {
  light: {
    text: "#171717",
    tint: "#171717",
    background: "#ffffff",
    foreground: "#171717",
    card: "#f5f5f5",
    cardForeground: "#171717",
    primary: "#0a0a0a",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#e8e8e8",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    highlight: "#171717",
  },
  dark: {
    text: "#ededed",
    tint: "#ededed",
    background: "#0a0a0a",
    foreground: "#ededed",
    card: "#141414",
    cardForeground: "#ededed",
    primary: "#ededed",
    primaryForeground: "#0a0a0a",
    secondary: "#1f1f1f",
    secondaryForeground: "#ededed",
    muted: "#1f1f1f",
    mutedForeground: "#888888",
    accent: "#1f1f1f",
    accentForeground: "#ededed",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
    highlight: "#ffffff",
  },
  radius: 4,
  online: "#4ade80",
};

export default colors;
