const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#0a0a0a",
    background: "#0690d4",
    foreground: "#0a0a0a",
    card: "rgba(0,0,0,0.08)",
    cardForeground: "#0a0a0a",
    primary: "#0a0a0a",
    primaryForeground: "#ffffff",
    secondary: "rgba(0,0,0,0.06)",
    secondaryForeground: "#0a0a0a",
    muted: "rgba(0,0,0,0.06)",
    mutedForeground: "rgba(0,0,0,0.65)",
    accent: "rgba(0,0,0,0.1)",
    accentForeground: "#0a0a0a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "rgba(0,0,0,0.2)",
    input: "rgba(0,0,0,0.2)",
    highlight: "#0a0a0a",
  },
  dark: {
    text: "#ededed",
    tint: "#ededed",
    background: "#111111",
    foreground: "#ededed",
    card: "#1a1a1a",
    cardForeground: "#ededed",
    primary: "#ededed",
    primaryForeground: "#0a0a0a",
    secondary: "#1f1f1f",
    secondaryForeground: "#ededed",
    muted: "#1f1f1f",
    mutedForeground: "#8a8a8a",
    accent: "#1f1f1f",
    accentForeground: "#ededed",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#2a2a2a",
    highlight: "#ffffff",
  },
  radius: 4,
  online: "#4ade80",
};

export default colors;
